# Generated by Django 4.2 on 2025-12-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
