# Generated by Django 4.2 on 2025-12-26 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pendinguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
        migrations.AddField(
            model_name='business',
            name='business_image_url',
            field=models.URLField(blank=True, db_column='business_image_url', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_logo_url',
            field=models.URLField(blank=True, db_column='business_logo_url', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.URLField(blank=True, db_column='product_image_url', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image_url',
            field=models.URLField(blank=True, db_column='service_image_url', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, db_column='profile_image_url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.business')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_favorite',
            },
        ),
    ]
