# Generated by Django 4.2 on 2025-12-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_product_image_remove_review_product_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE business_business ADD COLUMN view_count integer DEFAULT 0 NOT NULL;",
            reverse_sql="ALTER TABLE business_business DROP COLUMN view_count;"
        ),
    ]
