# Generated by Django 4.2 on 2025-12-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fix_missing_view_count'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE business_favorite ADD COLUMN IF NOT EXISTS service_id bigint REFERENCES business_service(id) DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE business_favorite ADD COLUMN IF NOT EXISTS product_id bigint REFERENCES business_product(id) DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            ALTER TABLE business_favorite DROP COLUMN IF EXISTS service_id;
            ALTER TABLE business_favorite DROP COLUMN IF EXISTS product_id;
            """
        ),
    ]
