# Generated by Django 4.2 on 2025-12-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fix_favorite_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_image_url',
            new_name='business_image',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_logo_url',
            new_name='business_logo',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_image',
            field=models.ImageField(blank=True, db_column='business_image_url', null=True, upload_to='businesses/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_logo',
            field=models.ImageField(blank=True, db_column='business_logo_url', null=True, upload_to='businesses/logos/'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
