# Generated by Django 4.2 on 2025-12-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fix_nullable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, db_column='product_image_url', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, db_column='service_image_url', null=True, upload_to='services/'),
        ),
    ]
