# Generated by Django 4.2 on 2025-12-26 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_profile_image_url_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_new_review', models.BooleanField(default=True, help_text='SMS when someone reviews your business')),
                ('email_new_review', models.BooleanField(default=True, help_text='Email when someone reviews your business')),
                ('sms_business_verified', models.BooleanField(default=True, help_text='SMS when business gets verified')),
                ('email_business_verified', models.BooleanField(default=True, help_text='Email when business gets verified')),
                ('sms_business_featured', models.BooleanField(default=True, help_text='SMS when business is featured')),
                ('email_business_featured', models.BooleanField(default=True, help_text='Email when business is featured')),
                ('sms_weekly_performance', models.BooleanField(default=False, help_text='SMS weekly performance digest')),
                ('email_weekly_performance', models.BooleanField(default=True, help_text='Email weekly performance digest')),
                ('sms_low_trust_score', models.BooleanField(default=True, help_text='SMS when trust score drops')),
                ('email_low_trust_score', models.BooleanField(default=True, help_text='Email when trust score drops')),
                ('sms_new_businesses', models.BooleanField(default=False, help_text='SMS about new businesses in favorited categories')),
                ('email_new_businesses', models.BooleanField(default=True, help_text='Email about new businesses')),
                ('sms_featured_weekly', models.BooleanField(default=False, help_text='SMS featured business of the week')),
                ('email_featured_weekly', models.BooleanField(default=True, help_text='Email featured business of the week')),
                ('sms_special_offers', models.BooleanField(default=True, help_text='SMS special offers from favorited businesses')),
                ('email_special_offers', models.BooleanField(default=True, help_text='Email special offers')),
                ('sms_church_announcements', models.BooleanField(default=True, help_text='SMS church/community announcements')),
                ('email_church_announcements', models.BooleanField(default=True, help_text='Email church announcements')),
                ('sms_weekly_digest', models.BooleanField(default=False, help_text='SMS weekly community digest')),
                ('email_weekly_digest', models.BooleanField(default=True, help_text='Email weekly community digest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preference',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_review', 'New Review'), ('business_verified', 'Business Verified'), ('business_featured', 'Business Featured'), ('low_trust_score', 'Low Trust Score'), ('weekly_performance', 'Weekly Performance'), ('new_business', 'New Business'), ('featured_weekly', 'Featured Business'), ('special_offer', 'Special Offer'), ('church_announcement', 'Church Announcement')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to navigate when clicked', max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.business')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_715af4_idx'),
        ),
    ]
