# Generated by Django 4.2 on 2025-12-26 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_notificationpreference_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('referrer', models.CharField(blank=True, help_text='HTTP Referer header', max_length=500, null=True)),
                ('referrer_source', models.CharField(blank=True, db_index=True, help_text='Categorized source: Direct, Google, Facebook, etc.', max_length=100, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='api.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_page_view',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['business', '-viewed_at'], name='business_pa_busines_86d5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['business', 'referrer_source'], name='business_pa_busines_a0bc32_idx'),
        ),
    ]
