# Generated by Django 4.2 on 2025-12-26 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pageview_pageview_business_pa_busines_86d5b6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_rewards', to='api.business')),
            ],
            options={
                'db_table': 'awarded_reward',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCampaignProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points_earned', models.IntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business_campaign_progress',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Campaign name (e.g., 'Profile Completion Challenge')", max_length=255)),
                ('description', models.TextField(help_text='What is this campaign about?')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_points_available', models.IntegerField(default=0, help_text='Sum of all action points')),
                ('participants_count', models.IntegerField(default=0, help_text='Number of businesses participating')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add_logo', 'Add Business Logo'), ('add_banner', 'Add Business Banner Image'), ('add_description', 'Add Business Description'), ('add_product', 'Add First Product'), ('add_service', 'Add First Service'), ('add_5_products', 'Add 5 Products'), ('add_5_services', 'Add 5 Services'), ('get_verified', 'Get Church Verified'), ('get_first_review', 'Receive First Review'), ('get_5_reviews', 'Receive 5 Reviews'), ('add_social_links', 'Add Social Media Links'), ('complete_profile', 'Complete 100% of Profile')], max_length=50)),
                ('action_name', models.CharField(help_text='Custom name for this action', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=10, help_text='Points earned for completing this action')),
                ('order', models.IntegerField(default=0, help_text='Display order in campaign')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.campaign')),
            ],
            options={
                'db_table': 'campaign_action',
                'ordering': ['campaign', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('badge', 'Badge'), ('featured', 'Featured Listing'), ('discount', 'Platform Discount'), ('boost', 'Profile Boost'), ('priority', 'Priority Support')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_points', models.IntegerField(help_text='Points needed to unlock this reward')),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_days', models.IntegerField(blank=True, help_text='How long reward lasts (for time-limited rewards)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_to', models.ManyToManyField(related_name='rewards_earned', through='api.AwardedReward', to='api.business')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='api.campaign')),
            ],
            options={
                'db_table': 'reward',
                'ordering': ['required_points'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='When to start featuring this business')),
                ('end_date', models.DateTimeField(help_text='When to stop featuring this business')),
                ('priority', models.IntegerField(default=0, help_text='Higher number = shown first')),
                ('featured_on_homepage', models.BooleanField(default=True, help_text='Show on homepage featured section')),
                ('featured_in_directory', models.BooleanField(default=True, help_text='Show at top of directory')),
                ('featured_in_category', models.BooleanField(default=False, help_text='Show at top of its category')),
                ('reason', models.TextField(blank=True, help_text='Why is this business featured? (internal note)', null=True)),
                ('is_paid_feature', models.BooleanField(default=False, help_text='Is this a paid featured listing?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_listings', to='api.business')),
                ('campaign', models.ForeignKey(blank=True, help_text='Link to campaign if featured as reward', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campaign')),
                ('selected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses_featured', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'featured_business',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompletedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.IntegerField(help_text='Points earned at time of completion')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaignaction')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_actions', to='api.businesscampaignprogress')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'completed_action',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddField(
            model_name='businesscampaignprogress',
            name='actions_completed',
            field=models.ManyToManyField(related_name='completed_by', through='api.CompletedAction', to='api.campaignaction'),
        ),
        migrations.AddField(
            model_name='businesscampaignprogress',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_progress', to='api.business'),
        ),
        migrations.AddField(
            model_name='businesscampaignprogress',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_progress', to='api.campaign'),
        ),
        migrations.AddField(
            model_name='awardedreward',
            name='campaign_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businesscampaignprogress'),
        ),
        migrations.AddField(
            model_name='awardedreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reward'),
        ),
        migrations.AddIndex(
            model_name='featuredbusiness',
            index=models.Index(fields=['start_date', 'end_date'], name='featured_bu_start_d_c0b8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredbusiness',
            index=models.Index(fields=['-priority'], name='featured_bu_priorit_416058_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='completedaction',
            unique_together={('progress', 'action')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignaction',
            unique_together={('campaign', 'action_type')},
        ),
        migrations.AlterUniqueTogether(
            name='businesscampaignprogress',
            unique_together={('business', 'campaign')},
        ),
        migrations.AlterUniqueTogether(
            name='awardedreward',
            unique_together={('business', 'reward')},
        ),
    ]
