# Generated by Django 4.2 on 2025-12-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_awardedreward_businesscampaignprogress_campaign_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pendinguser',
            table='pending_user',
        ),
    ]
