# Generated by Django 4.2 on 2025-12-29 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_pendinguser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('account_size', models.DecimalField(decimal_places=2, help_text='Starting balance (e.g., 50000)', max_digits=12)),
                ('profit_target', models.DecimalField(decimal_places=2, help_text='Profit needed to pass', max_digits=12)),
                ('max_drawdown', models.DecimalField(decimal_places=2, help_text='Maximum total loss allowed', max_digits=12)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, help_text='Maximum loss allowed in a single day', max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of the plan', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('min_trading_days', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trading_plan',
            },
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeovate_account_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tradeovate_username', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('active', 'Active'), ('failed', 'Failed'), ('passed', 'Passed'), ('funded', 'Funded')], default='pending', max_length=20)),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('current_drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tradingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_account',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeovate_id', models.CharField(max_length=255, unique=True)),
                ('symbol', models.CharField(max_length=50)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('quantity', models.IntegerField()),
                ('pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='api.tradingaccount')),
            ],
            options={
                'db_table': 'trading_trade',
                'ordering': ['-entry_time'],
            },
        ),
    ]
