# Generated by Django 4.2 on 2025-12-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tradingplan_tradingaccount_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(db_column='image_url', upload_to='businesses/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.business')),
            ],
            options={
                'db_table': 'business_image',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='TradingAccount',
        ),
        migrations.DeleteModel(
            name='TradingPlan',
        ),
    ]
