# Generated by Django 4.2 on 2025-12-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_businessimage_remove_tradingaccount_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='report_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='weekly', max_length=10),
        ),
    ]
