# Generated by Django 4.2 on 2025-12-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_notification_preferences'),
        ('api', '0019_review_product_review_service_review_updated_at'),
    ]

    operations = [
    ]
